### ISSUE TITLE
readwritesqlite_meta, _log and _init should not be viewable

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/slobr#25]
these tables should not be displayed by slobr since we don't want the user modifying them

**Comment by sebdalgarno** [comment]
fixed by adding readwrimtesqlite dependency

**Comment by joethorley** [comment]
I

**Comment by joethorley** [comment]
I think readwritesqlite should just be in suggests (cos of its dependence on sf) and the filtering should be done based solely on name ie do not show tables with the following names.

.log_table_name <- "readwritesqlite_log"
.meta_table_name <- "readwritesqlite_meta"
.init_table_name <- "readwritesqlite_init"

These names shouldn't change in readwritesqlite but as an insurance there should be a test where readwritesqlite writes to a table (creating the three tables) and it should be checked that only the table that is written to is recognized by slobr.

**Comment by joethorley** [comment]
see https://github.com/poissonconsulting/slobr/issues/29

**Comment by sebdalgarno** [comment]
done and added to tests
