### ISSUE TITLE
use readwritesqlite to read table?

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/slobr#29]
currently uses DBI and works. Would there be a benefit to using readwrimtesqlite instead - (already a dependency)

**Comment by joethorley** [comment]
It would add metadata to the table - which if the user had been writing the table using readwritesqlite would be preserved - so this would be an advantage - however readwritesqlite has sf as a dependency which is a "costly" dependency as rgdal etc have to be installed. I would add readwritesqlite to the suggests and by default set meta = FALSE. If the user sets meta = TRUE (through a check box)  then I would use something like

```
  if(meta) {
    if(!requireNamespace("readwritesqlite", quietly = TRUE))
      err("Package readwritesqlite is required to read tables with meta data.")
    data <- rws_read_table(table_name, meta = TRUE, conn = conn)
} else
     data <- DBI::dbReadTable(conn, table_name)
```

**Comment by sebdalgarno** [comment]
removed readwriteswlite dependency
